SYNOPSIS
========
   void raise_error(stringÂ arg)

DESCRIPTION
===========
   Abort execution. If the current program execution was initiated by 
   catch(E), that catch expression will return arg as error code, else the arg
   will printed as error message.

   This is very similar to throw(E), but while throw(E) is intended to be 
   called inside catch(E), raise_error(E) can be called anywhere. Furthermore,
   raise_error(E) includes the complete error handling with generation of a 
   stack backtrace, making it a very expensive function.

SEE ALSO
========
   catch(E), throw(E)
